sudo: false

language: go

go:
  - 1.10.x

before_script:
  - make prepare
  - make js

script:
  - make golint
  - make gotest
  - make build
  - make plugin_relic
  - make plugin_sound

cache:
  directories:
    - node_modules
