sudo: false

language: go

go:
  - 1.12.x
  - stable

before_script:
  - go get -u golang.org/x/lint/golint
  - make golint
  - make gotest

script:
  - make build
  - make plugin_fake
  - make plugin_relic

env:
  global:
  - GO111MODULE=on
